
import java.awt.Color;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class splash extends javax.swing.JFrame implements Runnable {

   
    public splash() {
        initComponents();
        jProgressBar1.setForeground(Color.GREEN);
    }
    
     @Override
    public void run() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        Hacker = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        PrName = new javax.swing.JLabel();
        ValueLoading = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Net Caerus Loading");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        BackGroundPanel.setBackground(new java.awt.Color(153, 255, 153));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(700, 400));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hacker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Assests/000123456.png"))); // NOI18N
        BackGroundPanel.add(Hacker, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 200, 230));
        BackGroundPanel.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, 720, 20));

        LoadingLabel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setText("Loading.....");
        BackGroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        PrName.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        PrName.setForeground(new java.awt.Color(255, 255, 255));
        PrName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrName.setText("Net Caerus");
        BackGroundPanel.add(PrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 300, 50));

        ValueLoading.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        ValueLoading.setForeground(new java.awt.Color(255, 255, 204));
        ValueLoading.setText("0%");
        BackGroundPanel.add(ValueLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 350, 60, -1));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Assests/BBBBBBBBB1.png"))); // NOI18N
        BackgroundImage.setText("jLabel1");
        BackGroundPanel.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        splash sp = new splash();
        sp.setVisible(true);
        
        try{
            
            for(int i=0;i<=100;i++){
                Thread.sleep(60);
                sp.ValueLoading.setText(i +"%");
                
                if(i==10){
                    sp.LoadingLabel.setText("Turning on Modules...");
                }
                 if(i==20){
                    sp.LoadingLabel.setText("Loading on Modules...");
                }
                  if(i==50){
                    sp.LoadingLabel.setText("Connecting To Database...");
                }
                   if(i==80){
                    sp.LoadingLabel.setText("Launching Application...");
                }
                   sp.jProgressBar1.setValue(i);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        
        Login me = new Login();
        me.setVisible(true);
        //dispose();
      
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel Hacker;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel PrName;
    private javax.swing.JLabel ValueLoading;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

   
}
